apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
spec:
  type: NodePort
  selector:
    app: pgadmin4
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-config
  namespace: default
data:
  PGADMIN_DEFAULT_EMAIL: "user@goilerplate.com"
  PGADMIN_DEFAULT_PASSWORD: "1234"
  PGADMIN_LISTEN_PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: someday94/goilerplate-pgadmin4:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: pgadmin4-config
        imagePullPolicy: Always