name: cd

on: 
  push:
    tags:
      - '*'

jobs:
  Build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: someday94
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./k8s/containers/api.Dockerfile
          push: true
          tags: someday94/goilerplate-api:${{ github.ref_name }}

#  Deploy:
#    name: Deploy to K8S
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to K8S
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: ${{ secrets.CLOUD_HOST }}
#          username: ${{ secrets.CLOUD_USERNAME }}
#          password: ${{ secrets.CLOUD_PASSWORD }}
#          port: ${{ secrets.CLOUD_PORT }}
#          script: kubectl set image deploy/api api=someday94/goilerplate-api:${{ github.ref_name }}