name: ci

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Config File
        run: cp ./env/production.env ./.env

      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .